---
functional:
  - Пользователи должны иметь возможность зарегистрироваться.
  - Должна быть возможность авторизации с помощью логина/пароля, указанных при регистрации, github, discord.
  - В личном кабинете пользователя должна отображаться персональная информация и статистика пользователя.
  - Пользователи имеют личный рейтинг, полученный вследствии участия в играх с другими пользователями.
  - Пользователи должны иметь возможность соревноваться друг с другом в реальном времени.
  - Пользователи должны видеть написание кода друг друга в реальном времени.
  - Пользователям должна быть доступна игра с ботом.
  - Пользователи должны иметь возможность выбирать язык для программирования во время игры.
  - Пользователи должны иметь возможность поиска и выбора игры по виду и уровню сложности.
  - Другие пользователи должны иметь возможность следить за ходом игры.
  - Задачи должны быть доступны на двух языках — русском и английском. 
non-functional:
  - Приложение должно быть оптимизировано для быстрой работы.
  - Приложение должно быть безопасным и защищать персональные данные пользователей.
  - Приложение должно быть адаптировано для мобильных устройств.
  - Приложение должно быть протестировано на совместимость с последними версиями популярных браузеров (Chrome, Firefox, Safari, Edge).
  - Приложение должно выдерживать нагрузку до 1000 одновременных пользователей.
implicit:
  - Пользовательский интерфейс должен быть интуитивно понятным и легким в использовании.
  - Разработка и добавление новых функций должны учитывать предложения пользователей.
  - Ожидается, что будет корректно обрабатывать ошибки и предоставлять пользователю понятные сообщения об ошибках.
  - Ожидается корректная работа элементов пользовательского интерфейса.
